### Users list
GET {{url}}/users

### Movies list
GET {{url}}/movies

### Add new movie
POST {{url}}/movies
Content-Type: application/json

{
  "title": "Back to the Future"
}

### Add new movie (invalid body: no `title`)
POST {{url}}/movies
Content-Type: application/json

{
}
